= Quick UI Checklist
:sectnums:
:sectnumlevels: 4


This is is a shortlist of the most relevant and easy to apply Eclipse 
link:eclipse_ui_guidelines.adoc[*User Interface Guidelines*].  
Start by using this list, referring to the linked guideline items for details, 
then use the link:eclipse_ui_full_checklist.adoc[Full Checklist] 
for additional guidance.  For comments please use the 
https://github.com/eclipse-platform/ui-best-practices/issues[UI Best Practices GitHub Issues].

== Views & Editors

. Put only the most commonly used commands on the view toolbar. 
  Any command on a toolbar must also appear in a menu, either the window menu, 
  context menu or the view menu.  
  (xref:eclipse_ui_guidelines.adoc#guideline7.12[Guideline 7.12])
. Use the view pulldown menu for commands not tied to selection 
  (xref:eclipse_ui_guidelines.adoc#guideline7.10[Guideline 7.10]). 
  Fill the context menu with selection oriented actions 
  (xref:eclipse_ui_guidelines.adoc#guideline7.13[Guideline 7.13]).
. If a view or editor has support for Cut, Copy, Paste, or any of the global commands, 
  these commands must be executable from the same commands in the window menu bar and toolbar.
  (xref:eclipse_ui_guidelines.adoc#guideline6.9[Guideline 6.9]), 
  (xref:eclipse_ui_guidelines.adoc#guideline7.19[Guideline 7.19])
    
. Modifications of workspace resources made in an editor should follow an open-save-close lifecycle model
  (xref:eclipse_ui_guidelines.adoc#guideline6.2[Guideline 6.2]), 
  whereas modifications made within a view should be saved immediately
  (xref:eclipse_ui_guidelines.adoc#guideline7.2[Guideline 7.2]).
   
. Persist the state of each view between sessions 
  (xref:eclipse_ui_guidelines.adoc#guideline7.20[Guideline 7.20]).

== Wizards & Dialogs

. Start a wizard with a prompt, not an error message. 
  (xref:eclipse_ui_guidelines.adoc#guideline5.3[Guideline 5.3])
  
. Seed the fields within a wizard using the current workbench state. 
  (xref:eclipse_ui_guidelines.adoc#guideline5.4[Guideline 5.4])
  
. When a dialog opens, set the initial focus to the first input control in the container. 
  If there are no input controls, the initial focus should be assigned to the default button 
  (xref:eclipse_ui_guidelines.adoc#guideline4.1[Guideline 4.1])
  
. Use a Browse Button whenever an existing object is referenced in a wizard. 
  (xref:eclipse_ui_guidelines.adoc#guideline5.8[Guideline 5.8])

== Workbench & Preferences

. Use Headline style capitalization for menus, tooltip and all titles, 
  including those used for windows, dialogs, tabs, column headings and push buttons 
  (xref:eclipse_ui_guidelines.adoc#guideline1.5[Guideline 1.5]).  
  Use Sentence style capitalization for all control labels in a dialog or window, 
  including those for check boxes, radio buttons, group labels, and simple text fields 
  (xref:eclipse_ui_guidelines.adoc#guideline1.6[Guideline 1.6]).
  
. Follow the visual style established for Eclipse UI graphics 
  (xref:eclipse_ui_guidelines.adoc#guideline2.1[Guideline 2.1]). 
  Re-use the color palette 
  (xref:eclipse_ui_guidelines.adoc#guideline2.2[Guideline 2.2]) 
  and visual concepts to maintain consistent representation and meaning across Eclipse plug-ins 
  (xref:eclipse_ui_guidelines.adoc#guideline2.3[Guideline 2.3]).  
  
. If you must create a new preference group, use the root page for frequently used preferences, 
  or those preferences which have wide spread effect. Specialize within the sub pages. 
  The root preference page should not be blank. 
  (xref:eclipse_ui_guidelines.adoc#guideline2.2[Guideline 2.2])

